---
- name: Configure Local DevOps Server
  hosts: local
  become: true

  tasks:

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure Nginx is enabled and started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Check Nginx status
      ansible.builtin.command: systemctl is-active nginx
      register: nginx_status
      changed_when: false

    - name: Display Nginx status
      ansible.builtin.debug:
        msg: "Nginx status is {{ nginx_status.stdout }}"
