name: DevOps CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: 05-nginx-reverse-proxy
        run: npm install

      - name: Run tests
        working-directory: 05-nginx-reverse-proxy
        run: npm test

      - name: Check application files
        working-directory: 05-nginx-reverse-proxy
        run: |
          test -f server.js
          test -f package.json
          test -f Dockerfile

      - name: Build Docker image
        working-directory: 05-nginx-reverse-proxy
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-nginx-app:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-nginx-app:latest \
            .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-nginx-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-nginx-app:latest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devops-app

            docker compose pull app

            docker compose up -d

            docker image prune -f

            docker compose ps
